# Site settings
title: Welcome
email: atyagi@buffalo.edu
url: https://abhimanyu1993.github.io
description: "Hi. My name is Abhimanyu Tyagi. I am a passionate web developer with over a varied experience making websites for my clients using CMS softwares as well as bootstrap frameworks. I am well versed with CSS, JavaScript, HTML and AJAX for making my clients' websites."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: www.abhimanyu1993.github.io

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/abhimanyu.tyagi1993
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
    title: twitter
    url: https://twitter.com/abhityagi93
  - title: linkedin
    url: https://www.linkedin.com/in/tyagiabhimanyu
  - title: github
    url: https://github.com/abhimanyu1993/abhimanyu1993.github.io

# Build settings
markdown: kramdown
permalink: pretty
